#!/usr/bin/env python3
"""
Document Archiver - Archives old documentation.

Usage:
    python archive_docs.py [project_path] [--days DAYS] [--archive-dir ARCHIVE_DIR]

This script:
1. Finds documents older than specified days
2. Moves them to an archive directory
3. Creates an index of archived documents
4. Optionally creates redirect files
"""

import argparse
import os
import re
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional


@dataclass
class ArchiveCandidate:
    """Represents a document that should be archived."""
    file_path: str
    last_modified: datetime
    days_since_modified: int
    reason: str


class DocumentArchiver:
    """Archives old documentation."""

    # File types to consider
    DOC_EXTENSIONS = {'.md', '.txt', '.rst', '.adoc'}

    # Patterns indicating stale content
    STALE_PATTERNS = [
        (r'202[0-3]-', 'Old version reference'),
        (r'legacy', 'Legacy system'),
        (r'deprecated', 'Deprecated content'),
        (r'outdated', 'Outdated content'),
        (r'TODO.*202[0-3]', 'Old TODO'),
    ]

    def __init__(self, project_path: str):
        self.project_path = Path(project_path)

    def find_archive_candidates(self, days: int = 365,
                                 archive_dir: str = "docs/archive") -> list[ArchiveCandidate]:
        """Find documents that should be archived."""
        candidates = []
        archive_path = self.project_path / archive_dir

        for ext in self.DOC_EXTENSIONS:
            for file_path in self.project_path.rglob(f'*{ext}'):
                if 'node_modules' in str(file_path) or '__pycache__' in str(file_path):
                    continue
                if archive_dir in str(file_path):
                    continue  # Skip already archived files

                try:
                    stat = file_path.stat()
                    last_modified = datetime.fromtimestamp(stat.st_mtime)
                    days_since = (datetime.now() - last_modified).days

                    if days_since > days:
                        reason = f"Not modified in {days_since} days"
                    else:
                        # Check for stale patterns
                        content = file_path.read_text()
                        for pattern, pattern_reason in self.STALE_PATTERNS:
                            if re.search(pattern, content, re.IGNORECASE):
                                reason = pattern_reason
                                break
                        else:
                            continue  # Not a candidate

                    candidates.append(ArchiveCandidate(
                        file_path=str(file_path),
                        last_modified=last_modified,
                        days_since_modified=days_since,
                        reason=reason
                    ))
                except Exception:
                    pass

        return sorted(candidates, key=lambda x: x.days_since_modified, reverse=True)

    def archive_document(self, file_path: str, archive_dir: str = "docs/archive",
                          create_redirect: bool = True) -> bool:
        """Archive a single document."""
        source = Path(file_path)
        if not source.exists():
            return False

        archive_path = self.project_path / archive_dir
        archive_path.mkdir(parents=True, exist_ok=True)

        # Create date-based subdirectory
        date_dir = archive_path / datetime.now().strftime("%Y-%m")
        date_dir.mkdir(exist_ok=True)

        # Move file
        relative_path = source.relative_to(self.project_path)
        destination = date_dir / source.name
        shutil.move(str(source), str(destination))

        # Create redirect if requested
        if create_redirect:
            self._create_redirect(source, destination, relative_path)

        # Update index
        self._update_index(archive_path, destination, relative_path)

        return True

    def _create_redirect(self, source: Path, destination: Path, original_path: Path):
        """Create a redirect file pointing to archived location."""
        redirect_content = f"""---
redirect_to: {destination.relative_to(self.project_path)}
last_updated: {datetime.now().isoformat()}
---

# Document Archived

This document has been archived.

**Original location:** `{original_path}`
**Archived location:** `{destination}`

If you need to view the archived version, see: {destination}

---
*This file was automatically generated by the document archiver.*
"""
        source.write_text(redirect_content)

    def _update_index(self, archive_path: Path, archived_file: Path, original_path: Path):
        """Update the archive index."""
        index_file = archive_path / "INDEX.md"
        timestamp = datetime.now().isoformat()

        entry = f"- [{original_path}]({archived_file}) - archived {timestamp}\n"

        if index_file.exists():
            content = index_file.read_text()
            index_file.write_text(content + "\n" + entry)
        else:
            index_file.write_text(f"# Archived Documents\n\n{entry}")

    def archive_all(self, candidates: list[ArchiveCandidate], archive_dir: str = "docs/archive",
                    auto_confirm: bool = False) -> int:
        """Archive multiple documents."""
        if not candidates:
            print("No documents to archive.")
            return 0

        print(f"Found {len(candidates)} document(s) to archive:\n")

        for c in candidates:
            print(f"  - {c.file_path}")
            print(f"    {c.reason} ({c.days_since_modified} days old)")
            print()

        if not auto_confirm:
            response = input(f"Archive all {len(candidates)} documents? [y/N]: ")
            if response.lower() != 'y':
                print("Aborted.")
                return 0

        archived = 0
        for candidate in candidates:
            if self.archive_document(candidate.file_path, archive_dir):
                archived += 1
                print(f"Archived: {candidate.file_path}")

        print(f"\nArchived {archived} document(s).")
        return archived

    def list_archived(self, archive_dir: str = "docs/archive") -> list[Path]:
        """List all archived documents."""
        archive_path = self.project_path / archive_dir
        if not archive_path.exists():
            return []

        archived = []
        for ext in self.DOC_EXTENSIONS:
            for file_path in archive_path.rglob(f'*{ext}'):
                if file_path.name != "INDEX.md":
                    archived.append(file_path)

        return sorted(archived)


def main():
    parser = argparse.ArgumentParser(description="Archive old documentation")
    parser.add_argument("project_path", nargs="?", default=".",
                        help="Path to project")
    parser.add_argument("--days", type=int, default=365,
                        help="Archive documents not modified in X days (default: 365)")
    parser.add_argument("--archive-dir", default="docs/archive",
                        help="Archive directory (default: docs/archive)")
    parser.add_argument("--list", action="store_true",
                        help="List documents that should be archived")
    parser.add_argument("--auto", action="store_true",
                        help="Auto-archive without confirmation")
    parser.add_argument("--restore", metavar="FILE",
                        help="Restore an archived document")

    args = parser.parse_args()

    archiver = DocumentArchiver(args.project_path)

    if args.restore:
        # Restore archived document
        archive_path = Path(args.restore)
        if archive_path.exists():
            original_name = archive_path.name
            # Try to find original location from content
            content = archive_path.read_text()
            redirect_match = re.search(r'redirect_to:\s*(.+)', content)
            if redirect_match:
                original_path = args.project_path / Path(redirect_match.group(1).strip()).parent / original_name
            else:
                original_path = Path(args.project_path) / original_name

            original_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(archive_path), str(original_path))
            print(f"Restored: {original_path}")
        else:
            print(f"File not found: {args.restore}")
        return 0

    if args.list:
        candidates = archiver.find_archive_candidates(args.days, args.archive_dir)
        if not candidates:
            print("No documents need archiving.")
        else:
            print(f"Documents that should be archived (>{args.days} days or stale):\n")
            for c in candidates:
                print(f"  - {c.file_path}")
                print(f"    {c.reason} ({c.days_since_modified} days old)")
        return 0

    # Default: find and optionally archive
    candidates = archiver.find_archive_candidates(args.days, args.archive_dir)
    archiver.archive_all(candidates, args.archive_dir, args.auto)


if __name__ == "__main__":
    sys.exit(main())
