const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const file='../src/strategy/interfaces/web/static/data-management.js';const x=fs.existsSync(require('node:path').resolve(__dirname,file))?require(file):{};
test('groups versions by security and searches symbol or Chinese name',()=>{assert.equal(typeof x.groupAssets,'function');const rows=[{id:'a',symbol:'600519.SH',name:'贵州茅台'},{id:'b',symbol:'600519.SH',name:'贵州茅台'},{id:'c',symbol:'002015.SZ',name:'协鑫能科'}];assert.equal(x.groupAssets(rows,'茅台')[0].versions.length,2);assert.equal(x.groupAssets(rows,'002015')[0].symbol,'002015.SZ');});
test('partial availability never describes full requested interval as ready',()=>{assert.equal(typeof x.readinessText,'function');assert.match(x.readinessText({status:'partial',start:'2024-01-02',end:'2025-12-31'}),/部分.*2024-01-02.*2025-12-31/);assert.match(x.readinessText({status:'blocked'}),/暂不可/);});
test('refresh request retains full qfq start and uses server China date',()=>{assert.equal(typeof x.updateRequest,'function');assert.deepEqual(x.updateRequest({symbol:'600519.SH',requested_start:'2024-01-02',start:'2024-01-03'},'2026-09-22'),{symbol:'600519.SH',start:'2024-01-02',end:'2026-09-22'});});
class Element {constructor(tag){this.tag=tag;this.children=[];this.textContent='';this.value='';this.dataset={};this.attrs={};this.classList={toggle(){}};}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=items;}setAttribute(k,v){this.attrs[k]=v;}removeAttribute(k){delete this.attrs[k];if(k==='min')this.min='';}scrollIntoView(){}focus(){}set innerHTML(v){throw Error('unsafe HTML');}}
const walk=n=>[n,...n.children.flatMap(walk)],text=n=>walk(n).map(e=>e.textContent).join(' ');
function setup(api=async()=>({}),selectDataset=()=>{}){const nodes={};global.document={createElement:t=>new Element(t),getElementById:id=>nodes[id]??=new Element('div'),querySelectorAll:()=>[]};const manager=x.create({api,selectDataset,refresh:async()=>{}});return {nodes,manager};}
test('no foundation still permits dates through today and shows missing dependencies',()=>{const {nodes,manager}=setup();manager.render({today:'2026-09-22',assets:[],foundations:[],legacy_versions:[]});assert.equal(nodes['download-end'].max,'2026-09-22');assert.equal(nodes['download-end'].value,'2026-09-22');assert.equal(nodes['download-start'].min,'');assert.match(text(nodes['data-overview']),/仍可下载行情/);});
test('blocked asset cannot prepare research but can refill complete update request',async()=>{const asset={id:'asset_a',symbol:'600519.SH',name:'<img>',requested_start:'2024-01-02',requested_end:'2026-09-01',start:'2024-01-03',end:'2026-09-01',readiness:{status:'blocked',reasons:['缺少广度']},preview:[]};const {nodes,manager}=setup(async()=>asset);manager.render({today:'2026-09-22',assets:[asset],foundations:[]});await manager.openAsset('asset_a');const list=walk(nodes['asset-detail']);assert.equal(list.find(n=>n.textContent==='准备可用区间并带入回测').disabled,true);assert.match(text(nodes['asset-detail']),/<img>/);list.find(n=>n.textContent==='更新至今日（重新下载完整区间）').onclick();assert.equal(nodes['download-start'].value,'2024-01-02');assert.equal(nodes['download-end'].value,'2026-09-22');});
test('late detail response cannot replace more recently chosen asset',async()=>{let release;const gate=new Promise(r=>release=r);const {nodes,manager}=setup(async path=>path.endsWith('/a')?gate:{id:'b',symbol:'B',readiness:{status:'blocked'}});manager.render({today:'2026-09-22',assets:[],foundations:[]});const pending=manager.openAsset('a');await manager.openAsset('b');release({id:'a',symbol:'A',readiness:{status:'blocked'}});await pending;assert.match(text(nodes['asset-detail']),/B · 行情详情/);assert.doesNotMatch(text(nodes['asset-detail']),/A · 行情详情/);});
test('prepared asset carries its security and overlap into backtest selection',async()=>{const asset={id:'asset_a',symbol:'600519.SH',name:'贵州茅台',readiness:{status:'ready',start:'2024-03-01',end:'2024-03-29'},preview:[]};let chosen;const {nodes,manager}=setup(async(path,body)=>body?{dataset_id:'managed_a',start:'2024-03-01',end:'2024-03-29'}:asset,(...args)=>chosen=args);manager.render({today:'2026-09-22',assets:[asset],foundations:[]});await manager.openAsset(asset.id);await walk(nodes['asset-detail']).find(n=>n.textContent==='准备可用区间并带入回测').onclick();assert.equal(chosen[1]?.symbol,'600519.SH');assert.equal(chosen[1]?.start,'2024-03-01');assert.equal(chosen[1]?.end,'2024-03-29');});
test('foundation update submits dates and clears temporary token',async()=>{let called;const {nodes,manager}=setup(async(path,body)=>{called={path,body};return {id:'x'};});manager.render({today:'2026-09-22',assets:[],foundations:[],foundation_updates:[]});nodes['foundation-start'].value='2026-01-01';nodes['foundation-end'].value='2026-09-21';document.getElementById('foundation-token').value='private-test';await nodes['foundation-form'].onsubmit({preventDefault(){}});assert.equal(called.path,'/api/foundation-updates');assert.deepEqual(called.body,{start:'2026-01-01',end:'2026-09-21',token:'private-test'});assert.equal(nodes['foundation-token'].value,'');assert.match(nodes['foundation-notice'].textContent,/已提交/);});
test('foundation polling preserves edited fields and reports failed update',()=>{const {nodes,manager}=setup();manager.render({today:'2026-09-22',assets:[],foundations:[],foundation_updates:[{id:'x',status:'running',request:{start:'2026-01-01',end:'2026-09-21'},progress:{message:'下载广度'}}]});assert.equal(manager.hasPending(),true);nodes['foundation-start'].value='2025-01-01';manager.render({today:'2026-09-22',assets:[],foundations:[],foundation_updates:[{id:'x',status:'failed',request:{},error:'权限不足'}]});assert.equal(manager.hasPending(),false);assert.equal(nodes['foundation-start'].value,'2025-01-01');assert.match(text(nodes['foundation-updates']),/权限不足/);});
