const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const file=path.resolve(__dirname,'../src/strategy/interfaces/web/static/timeline.js');const x=fs.existsSync(file)?require(file):{};
class Element{constructor(tag){this.tag=tag;this.children=[];this.attrs={};this.textContent='';this.open=false;}append(...n){this.children.push(...n);}replaceChildren(...n){this.children=n;}setAttribute(k,v){this.attrs[k]=v;}set innerHTML(v){throw Error('unsafe HTML');}}
const walk=n=>[n,...n.children.flatMap(walk)];const text=n=>walk(n).map(n=>n.textContent).join(' ');
function setup(callbacks={}){const root=new Element('div');global.document={createElement:t=>new Element(t),createElementNS:(_,t)=>new Element(t),getElementById:()=>root};return {root,view:x.create(callbacks)};}
const interval={start:'2024-01-01',end:'2024-01-10'};const asset={id:'v1',symbol:'600519.SH',name:'<img onerror=alert(1)>',coverage:{market:[interval],research:[{start:'2024-01-03',end:'2024-01-04'}],missing:[{start:'2024-01-05',end:'2024-01-08',reason:'缺广度'}]}};
test('date scale includes both ends and clips intervals to shared axis',()=>{assert.equal(typeof x.scaleSegment,'function');assert.deepEqual(x.scaleSegment({start:'2023-12-01',end:'2024-01-05'},interval),{x:0,width:500});assert.equal(x.scaleSegment({start:'2025-01-01',end:'2025-02-01'},interval),null);});
test('groups all versions without stitching same security',()=>{assert.equal(typeof x.groupAssets,'function');assert.equal(x.groupAssets([asset,{...asset,id:'v2'}])[0].versions.length,2);});
test('renders safe text, segmented SVG and explicit research/fill actions',()=>{assert.equal(typeof x.create,'function');let research,fill;const {root,view}=setup({onResearch:(...a)=>research=a,onFill:(...a)=>fill=a});view.render({...interval,index:[interval],breadth:[],common:[],conflicts:[{date:'2024-01-02',kind:'index',sources:['a','b']}]},[asset]);const nodes=walk(root);assert.match(text(root),/<img onerror=alert\(1\)>/);assert.ok(nodes.some(n=>n.tag==='rect'));nodes.find(n=>n.tag==='button'&&n.textContent.includes('研究此区间')).onclick();assert.deepEqual(research,['v1','2024-01-03','2024-01-04']);nodes.find(n=>n.tag==='button'&&n.textContent.includes('补齐')).onclick();assert.deepEqual(fill,['2024-01-05','2024-01-08']);assert.match(text(root),/不保证.*预热/);});
test('polling preserves expanded symbols and versions',()=>{const {root,view}=setup();view.render(interval,[asset]);const details=walk(root).filter(n=>n.tag==='details');details.forEach(n=>n.open=true);view.render(interval,[asset]);assert.ok(walk(root).filter(n=>n.tag==='details').every(n=>n.open));});
test('empty coverage explains absent data',()=>{const {root,view}=setup();view.render({},[]);assert.match(text(root),/暂无/);});

test('stock gaps route to quote refresh, not foundation updates',()=>{const nodes={};global.document={createElement:t=>new Element(t),createElementNS:(ns,t)=>new Element(t),getElementById:id=>nodes[id]??=new Element('div')};let market,base=false;const view=x.create({onFill:()=>base=true,onMarketFill:(...args)=>market=args});view.render({start:'2026-01-05',end:'2026-01-09'},[{id:'asset_x',symbol:'600519.SH',coverage:{missing:[{start:'2026-01-07',end:'2026-01-07',reason:'缺少证券行情'}]}}]);walk(nodes['coverage-timeline']).find(n=>n.tag==='button'&&n.textContent.includes('重新下载行情')).onclick();assert.equal(base,false);assert.equal(market[0],'asset_x');});
test('recommended timeline remains visible while alternative qfq histories start collapsed',()=>{const {root,view}=setup();view.render(interval,[asset,{...asset,id:'v2'}]);const security=root.children.find(n=>n.className==='timeline-security');assert.ok(security);assert.ok(security.children.some(n=>n.className==='timeline-row'));const history=security.children.find(n=>n.tag==='details'&&text(n).includes('其他与历史'));assert.equal(history.open,false);assert.equal(security.children.filter(n=>n.className==='timeline-row'&&text(n).includes('行情覆盖')).length,1);});
